# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Anti-Drone​
email: joao.g.firmino@tecnico.ulisboa.pt
description: >- # this means to ignore newlines until "baseurl:"
  Isto é só um teste mas tipo:
  Este projeto visa desenvolver um sistema de detecção e rastreamento de drones utilizando tecnologia de radar. O sistema será capaz de identificar a presença de drones em um determinado espaço aéreo, diferenciando-os de outras aeronaves  ou objetos em movimento. A solução utilizará algoritmos de processamento de sinais para analisar os ecos de radar e técnicas de aprendizado de máquina para classificar e prever a trajetória dos drones. O objetivo é aumentar a segurança em áreas sensíveis, como aeroportos, instalações militares e eventos públicos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: joaofirmino17
github_username:  JoaoFirmino17

# Build settings
theme: minima
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
